// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Jj8d_Ooywzwbdh76VCGNGLNcfNqxw8E',
    appId: '1:615555618361:web:35780685c1738f8f2a9fe8',
    messagingSenderId: '615555618361',
    projectId: 'ricevendo-4e1fe',
    authDomain: 'ricevendo-4e1fe.firebaseapp.com',
    storageBucket: 'ricevendo-4e1fe.firebasestorage.app',
    databaseURL: 'https://ricevendo-4e1fe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU36fFKT6jGC0HseeISAA1uUJFpbONqqI',
    appId: '1:615555618361:android:64ff12e8e1819c962a9fe8',
    messagingSenderId: '615555618361',
    projectId: 'ricevendo-4e1fe',
    storageBucket: 'ricevendo-4e1fe.firebasestorage.app',
    databaseURL: 'https://ricevendo-4e1fe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKULeYwaouiqAKPOkr7vz0kI1bJhLoAS4',
    appId: '1:615555618361:ios:a2b1f276f90520042a9fe8',
    messagingSenderId: '615555618361',
    projectId: 'ricevendo-4e1fe',
    storageBucket: 'ricevendo-4e1fe.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
    databaseURL: 'https://ricevendo-4e1fe-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKULeYwaouiqAKPOkr7vz0kI1bJhLoAS4',
    appId: '1:615555618361:ios:a2b1f276f90520042a9fe8',
    messagingSenderId: '615555618361',
    projectId: 'ricevendo-4e1fe',
    storageBucket: 'ricevendo-4e1fe.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3Jj8d_Ooywzwbdh76VCGNGLNcfNqxw8E',
    appId: '1:615555618361:web:62156a408a2401d62a9fe8',
    messagingSenderId: '615555618361',
    projectId: 'ricevendo-4e1fe',
    authDomain: 'ricevendo-4e1fe.firebaseapp.com',
    storageBucket: 'ricevendo-4e1fe.firebasestorage.app',
  );
}
